import { defineConfig } from '@pandacss/dev'

export default defineConfig({
  // Enable css reset generated by Panda
  preflight: true,

  // Where Panda should look for your style declarations
  include: [
    './src/**/*.{ts,tsx,js,jsx}',
  ],

  // Files to exclude from scanning
  exclude: [],

  // Directory where the generated CSS system will be saved
  outdir: 'styled-system',

  // Ensure JSX factory points to React
  jsxFramework: 'react',
})