import { defineConfig } from '@pandacss/dev'
import typographyPreset from "pandacss-preset-typography"

export default defineConfig({
  // Enable css reset generated by Panda
  preflight: true,

  // Where Panda should look for your style declarations
  include: [
    './src/**/*.{ts,tsx,js,jsx}',
  ],

  // Files to exclude from scanning
  exclude: [],

  // Directory where the generated CSS system will be saved
  outdir: 'styled-system',

  // Ensure JSX factory points to React
  jsxFramework: 'react',

  presets: [typographyPreset()],

  theme: {
    extend: {
      keyframes: {
        pulse: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.5 },
        },
      },
      animations: {
        pulse: 'pulse 2s infinite',
      },
    },
  },
})